# This is a basic workflow to help you get started with Actions

name: Download and commit app usage

# Controls when the workflow will run
on:
  schedule:
    - cron:  '0 6 * * *'

  workflow_dispatch:

jobs:
  downloadAndCheckin:
    name: Download and Checkin
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Node
      uses: actions/setup-node@v3
      
    - name: Download and format file
      run: node DownloadAppUsage.js
      
    - name: Set Git config
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "Github Actions"
    
